/// Flutter icons Viiticons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Viiticons
///      fonts:
///       - asset: fonts/Viiticons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Viiticons {
  Viiticons._();

  static const _kFontFam = 'ViitIcons';

  static const IconData next_arrow =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hide = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData view = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData facebook =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData face = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData profile_pic =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData calendar =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData share_eta =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData loyalty_program =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData feel_good =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData photo_camera =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData card = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData visa_card =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData master_card =
      const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData help_support =
      const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData payment = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData promo = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData notification =
      const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData cash = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData my_rides =
      const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData location =
      const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData loved = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData settings =
      const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData work = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData vitt_assistance =
      const IconData(0xe829, fontFamily: _kFontFam);
}
